#!/bin/bash

. color.sh
. input.sh
echo -e "${TEXT} ${BACKGROUND}"HOSTNAME" ${END} \e[0m" = "${TEXT2} ${BACKGROUND2}$(hostname) ${END}" 
echo -e "${TEXT} ${BACKGROUND}"TIMEZONE"${END}" ="${TEXT2} ${BACKGROUND2}${TIMEZONE}${END}" 
echo -e "${TEXT} ${BACKGROUND}"USER"${END}"="${TEXT2} ${BACKGROUND2}${USER}${END}" 
echo -e "${TEXT} ${BACKGROUND}"OS"${END}"="${TEXT2} ${BACKGROUND2}${OS}${END}" 
echo -e "${TEXT} ${BACKGROUND}"DATE"${END}"="${TEXT2} ${BACKGROUND2}${DATE}${END}" 
echo -e "${TEXT} ${BACKGROUND}"UPTIME"${END}"="${TEXT2} ${BACKGROUND2}${UPTIME}${END}" 
echo -e "${TEXT} ${BACKGROUND}"UPTIME_SEC"${END}"="${TEXT2} ${BACKGROUND2}${UPTIME_SEC}${END}" 
echo -e "${TEXT} ${BACKGROUND}"IP"${END}"="${TEXT2} ${BACKGROUND2}${IP}${END}" 
echo -e "${TEXT} ${BACKGROUND}"MASK"${END}"="${TEXT2} ${BACKGROUND2}${MASK}${END}" 
echo -e "${TEXT} ${BACKGROUND}"RAM_TOTAL"${END}"="${TEXT2} ${BACKGROUND2}${RAM_TOTAL}${END}" 
echo -e "${TEXT} ${BACKGROUND}"RAM_USED"${END}"="${TEXT2} ${BACKGROUND2}${RAM_USED}${END}" 
echo -e "${TEXT} ${BACKGROUND}"RAM_FREE"${END}"="${TEXT2} ${BACKGROUND2}${RAM_FREE}${END}" 
echo -e "${TEXT} ${BACKGROUND}"SPACE_ROOT"${END}"="${TEXT2} ${BACKGROUND2}${SPACE_ROOT}${END}" 
echo -e "${TEXT} ${BACKGROUND}"SPACE_ROOT_USED"${END}"="${TEXT2} ${BACKGROUND2}${SPACE_ROOT_USED}${END}" 
echo -e "${TEXT} ${BACKGROUND}"SPACE_ROOT_FREE"${END}"="${TEXT2} ${BACKGROUND2}${SPACE_ROOT_FREE}${END}" 
